
WITH CTE
    AS
    (
select ORIGIN,DESTINATION,TICKET_COUNT from tickets
UNION ALL
    SELECT DESTINATION AS ORIGIN,ORIGIN AS DESTINATION ,TICKET_COUNT from tickets
    WHERE ONEWAY_ROUND='R'
)
SELECT ORIGIN ,DESTINATION,SUM(TICKET_COUNT) Total_TIckets FROM CTE
GROUP BY ORIGIN ,DESTINATION
ORDER BY Total_TIckets desc
FETCH first row only 
--OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY

    