with cte as
    (
select * from income
union all
select * from  deduction
)
,cte1 as
    (
select EMP_ID,EMP_NAME,INCOME AS TRANS_TYPE,BASE_SALARY*A.PERCENTAGE/100 AMOUNT FROM SALARY CROSS JOIN cte A	
ORDER BY EMP_ID,TRANS_TYPE
),
    CTE2 AS
    (
SELECT A.EMP_NAME AS EMPLOYEE
    ,MAX(BASE_SALARY) AS BASIC
    ,MAX(CASE WHEN TRANS_TYPE='Allowance' THEN AMOUNT END) AS ALLOWANCE
    ,MAX(CASE WHEN TRANS_TYPE='Others' THEN AMOUNT END) AS Others
    ,MAX(CASE WHEN TRANS_TYPE='Insurance' THEN AMOUNT END) AS Insurance
    ,MAX(CASE WHEN TRANS_TYPE='Health' THEN AMOUNT END) AS Health
    ,MAX(CASE WHEN TRANS_TYPE='House' THEN AMOUNT END) AS House
     FROM cte1 A inner join SALARY B
ON A.EMP_ID=B.EMP_ID
GROUP BY A.EMP_NAME   
)
SELECT EMPLOYEE,BASIC,ALLOWANCE,OTHERS,BASIC+ALLOWANCE+OTHERS AS GROSS ,INSURANCE,HEALTH,HOUSE,
    INSURANCE+HEALTH+HOUSE AS TOTAL_DEDUCTIONS,BASIC-INSURANCE AS NETPAY FROM CTE2



