WITH CTE AS
    (
SELECT DEPTNO , ROW_NUMBER() OVER(ORDER BY EMPNO) SEQ 
    ,COUNT(*) OVER() CT
    --OVER(PARTITION BY DEPTNO ORDER BY DEPTNO)
    FROM EMP

    )
SELECT * FROM CTE
WHERE SEQ<=CT/2